---
- hosts: all
  ignore_errors: yes
  become: yes
  tasks: 
    - name: Create user
      user:
        name: Fokam
        comment: Fokam JP

    - name: Create directory
      file: 
       path: /tmp/devop-ans
       owner: Fokam
       state: directory
       mode: "0777"

    - name: Create file
      file:
       path: /tmp/ansible-class
       owner: Fokam
       state: touch
       mode: "0600"
